services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
      args:
        UID: ${UID}
        GID: ${GID}
    tty: true
    volumes:
      - ./src/app:/app/app
      - ./tests:/app/tests
      - ./scripts:/app/scripts
      - ./pyproject.toml:/app/pyproject.toml
      - ./uv.lock:/app/uv.lock
    environment:
      - SAMPLE_ENV_VAR=${SAMPLE_ENV_VAR}