#!/bin/bash
# -e: abort on error  -u: error on unset variables  -o pipefail: propagate pipe failures
set -euo pipefail
# This hook runs code checks inside the Docker container

# To set up this hook, run the following:
#   cp hooks/pre-commit .git/hooks/pre-commit
#   chmod +x .git/hooks/pre-commit

# To override this hook, add the following flag when committing:
#   git commit --no-verify


docker compose exec -T app /usr/bin/bash /app/scripts/code-checks.sh