name: CI/CD Pipeline

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  validate-codebase:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.9.3"
          enable-cache: true

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run code quality checks
        run: bash src/scripts/code-checks.sh src/app

      - name: Run bandit security checks
        run: uv run bandit -r src/app

      - name: Run tests with coverage
        run: bash src/scripts/run-tests.sh src/tests src/app